#!/bin/bash

# Copyright 2026 the Thnode Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

remove_trailing_whitespace() {
  # Remove trailing whitespace from the end of each line.
  sed -i 's/[[:space:]]\+$//' "$1"
}

ensure_file_has_trailing_newline() {
  # If there is not a newline at end of file, add one.
  [ -s "$1" ] && tail -c1 "$1" | read -r _ || true
  if [ $? -ne 0 ]; then
    echo >> "$1"
  fi
}

REPO_ROOT=$(git rev-parse --show-toplevel)

pushd ${REPO_ROOT}

SRC_FILES=$(find src -type d -name third_party -prune -o -type f \( -name '*.cpp' -o -name '*.c' -o -name '*.h' \) -print)
echo "${SRC_FILES}" | while read -r file; do
  clang-tidy -p _build "$file" --fix
  clang-format -i "$file"  # -i: in-place edit

  remove_trailing_whitespace "$file"
  ensure_file_has_trailing_newline "$file"
done

LIT_TEST_FILES=$(find test/lit -type f \( -name '*.cpp' -o -name '*.c' -o -name '*.h' \) -print)
echo "${LIT_TEST_FILES}" | while read -r file; do
  clang-format -i "$file"  # -i: in-place edit

  remove_trailing_whitespace "$file"
  ensure_file_has_trailing_newline "$file"
done

popd
